/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#9f403d",
        "surface-container-lowest": "#ffffff",
        "outline": "#737c7f",
        "primary-dim": "#485367",
        "on-surface-variant": "#586064",
        "on-primary-container": "#475266",
        "surface-dim": "#d1dce0",
        "tertiary-fixed-dim": "#c1d0e6",
        "surface-container-low": "#f1f4f6",
        "on-error": "#fff7f6",
        "secondary-fixed-dim": "#c5d6f0",
        "primary-container": "#d8e3fb",
        "primary": "#545f73",
        "on-error-container": "#752121",
        "on-primary": "#f6f7ff",
        "surface-container": "#eaeff1",
        "inverse-primary": "#dae6fe",
        "on-secondary-fixed": "#314055",
        "secondary-container": "#d3e4fe",
        "inverse-surface": "#0c0f10",
        "error-dim": "#4e0309",
        "on-tertiary-container": "#414f62",
        "surface-bright": "#f8f9fa",
        "tertiary": "#526073",
        "error-container": "#fe8983",
        "tertiary-fixed": "#cfdef5",
        "surface-tint": "#545f73",
        "on-tertiary-fixed-variant": "#4a596c",
        "primary-fixed": "#d8e3fb",
        "secondary-fixed": "#d3e4fe",
        "on-primary-fixed": "#354053",
        "on-secondary-container": "#435368",
        "on-secondary": "#f7f9ff",
        "outline-variant": "#abb3b7",
        "on-primary-fixed-variant": "#515c70",
        "secondary-dim": "#44546a",
        "secondary": "#506076",
        "on-tertiary": "#f7f9ff",
        "tertiary-dim": "#465467",
        "on-surface": "#2b3437",
        "surface": "#f8f9fa",
        "surface-container-highest": "#dbe4e7",
        "tertiary-container": "#cfdef5",
        "on-tertiary-fixed": "#2e3d4e",
        "primary-fixed-dim": "#cad5ed",
        "on-background": "#2b3437",
        "on-secondary-fixed-variant": "#4d5d73",
        "background": "#f8f9fa",
        "surface-variant": "#dbe4e7",
        "inverse-on-surface": "#9b9d9e",
        "surface-container-high": "#e2e9ec"
      },
      fontFamily: {
        "headline": ["Pretendard"],
        "body": ["Pretendard"],
        "label": ["Pretendard"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [],
}
